SQLsmith: prod Struct Reference
prod Struct Reference abstract
Base class for AST nodes.
#include <prod.hh>
Public Member Functions
prod (prod *parent)
virtual void indent (std::ostream &out)
Newline and indent according to tree level.
virtual void out (std::ostream &out)=0
Emit SQL for this production.
virtual void match ()
Check with the impedance matching code whether this production has been blacklisted and throw an exception.
virtual void accept (prod_visitor *v)
Visitor pattern for walking the AST.
virtual void fail (const char *reason)
Report a "failed to generate" error.
void retry ()
Increase the retry count and throw an exception when retry_limit is exceeded.
Public Attributes
struct prod * pprod
Parent production that instanciated this one.
struct scope * scope
Scope object to model column/table reference visibility.
int level
Level of this production in the AST. 0 for root node.
long retries = 0
Number of retries in this production.
long retry_limit = 100
Maximum number of retries allowed before reporting a failure to the Parent prod.
Detailed Description
Base class for AST nodes.
Definition at line 17 of file prod.hh.
Member Function Documentation
accept()
virtual void prod::accept (prod_visitor * v) inline virtual
Visitor pattern for walking the AST.
Make sure you visit all child production when deriving classes.
Reimplemented in common_table_expression, update_returning, merge_stmt, when_clause_insert, when_clause_update, when_clause, update_stmt, upsert_stmt, set_list, insert_stmt, delete_returning, delete_stmt, prepare_stmt, query_spec, select_list, from_clause, joined_table, expr_join_cond, table_subquery, window_function, bool_binop, exists_predicate, null_predicate, coalesce, funcall, and case_expr.
Definition at line 41 of file prod.hh.
Referenced by funcall::accept(), coalesce::accept(), window_function::accept(), from_clause::accept(), select_list::accept(), insert_stmt::accept(), set_list::accept(), and merge_stmt::accept().
Member Data Documentation
pprod
struct prod* prod::pprod
Parent production that instanciated this one.
May be NULL for top-level productions.
Definition at line 20 of file prod.hh.
retries
long prod::retries = 0
Number of retries in this production.
Child productions are generated speculatively and may fail.
Definition at line 27 of file prod.hh.
The documentation for this struct was generated from the following files:
prod.hh
prod.cc