SQLsmith: select_list Struct Reference
select_list Struct Reference
Public Member Functions
select_list (prod *p)
virtual void out (std::ostream &out)
Emit SQL for this production.
virtual void accept (prod_visitor *v)
Visitor pattern for walking the AST.
Public Member Functions inherited from prod
prod (prod *parent)
virtual void indent (std::ostream &out)
Newline and indent according to tree level.
virtual void match ()
Check with the impedance matching code whether this production has been blacklisted and throw an exception.
virtual void fail (const char *reason)
Report a "failed to generate" error.
void retry ()
Increase the retry count and throw an exception when retry_limit is exceeded.
Public Attributes
std::vector< shared_ptr< value_expr > > value_exprs
relation derived_table
int columns = 0
Public Attributes inherited from prod
struct prod * pprod
Parent production that instanciated this one.
struct scope * scope
Scope object to model column/table reference visibility.
int level
Level of this production in the AST. 0 for root node.
long retries = 0
Number of retries in this production.
long retry_limit = 100
Maximum number of retries allowed before reporting a failure to the Parent prod.
Detailed Description
Definition at line 116 of file grammar.hh.
Member Function Documentation
accept()
virtual void select_list::accept (prod_visitor * v) inline virtual
Visitor pattern for walking the AST.
Make sure you visit all child production when deriving classes.
Reimplemented from prod.
Definition at line 123 of file grammar.hh.
References prod::accept().
Referenced by query_spec::accept(), delete_returning::accept(), and update_returning::accept().
The documentation for this struct was generated from the following files:
grammar.hh
grammar.cc